### ISSUE TITLE
Feat : updating the title of the website which is Vite + React .

### ISSUE THREAD

**Issue by milanroy704** [shivamsouravjha/stock-frontend#11]
hey @shivamsouravjha

**Comment by milanroy704** [comment]
hey @shivamsouravjha if you assign this issue to me as i am ready to contribute in you repo.
I can create a best appropriate logo for the stockSight and update the name stockSight  at the title.
And don't forget to add the hacktoberfest level.

**Comment by shivamsouravjha** [comment]
Sure @milanroy704 feel free to pick the issue

**Comment by milanroy704** [comment]
i have  added something in your repo. please verify then i will send you PR
![image](https://github.com/user-attachments/assets/ce4688fe-caff-434d-b7c6-235e632be356)

**Comment by shivamsouravjha** [comment]
Insteas of this use the stag image

**Comment by milanroy704** [comment]
what is means i cant understand stag image

**Comment by shivamsouravjha** [comment]
I meant using this iamge https://github.com/shivamsouravjha/stock-frontend/blob/master/public/icon.png instead of s2

**Comment by prajesh9921** [comment]
Can I start working on this issue ?

**Comment by prajesh9921** [comment]
Created Pull Request please check.
