### ISSUE TITLE
Bug:reset button doesn't reset the searched or sorted data

### ISSUE THREAD

**Issue by iambijayd** [shivamsouravjha/stock-frontend#13]
![Screenshot 2024-10-07 210304](https://github.com/user-attachments/assets/6a15c406-a978-4b13-b821-a34c8e62c7a7)
After searching or sorting the data, when i try to reset it doesn't work

**Comment by shivamsouravjha** [comment]
https://github.com/shivamsouravjha/stock-frontend/issues/12


similar  issue with home page as well

**Comment by prajesh9921** [comment]
Hello, I wanted to check if this issue has been closed. If not, I'd be happy to work on it. Please let me know. Thank you!

**Comment by shivamsouravjha** [comment]
Hey @prajesh9921 currently an PR is opened around the same.

**Comment by prajesh9921** [comment]
Ok no issues
