### ISSUE TITLE
Fix the responsive behaviour on the result page

### ISSUE THREAD

**Issue by devjayprakash** [shivamsouravjha/stock-frontend#16]
Currently everything other than result page toolbar is responsive. We need to make it responsive.
![Screenshot 2024-10-08 at 7 22 27 AM](https://github.com/user-attachments/assets/8026d939-9d41-4ce1-af24-f57d3d81f5f6)

**Comment by ahmedmaher2481998** [comment]
Hi @devjayprakash I tried fixing this, review [PR] (https://github.com/shivamsouravjha/stock-frontend/pull/22)
