### ISSUE TITLE
Feature Request :  Add a table layout for the result section. 

### ISSUE THREAD

**Issue by devjayprakash** [shivamsouravjha/stock-frontend#19]
I think we should have a button to switch between grid layout and table layout in the toolbar in the result page. This helps the user to better compare stocks when they are sorted and in general as well.

**Comment by shivamsouravjha** [comment]
any design about how it would look like?

**Comment by devjayprakash** [comment]
> any design about how it would look like?
I guess we should use shadcn .. it would look something like this.. with the column names same as what we have now.
<img width="720" alt="image" src="https://github.com/user-attachments/assets/b68bca13-2228-4d1c-9bcb-183779b6bf10">

**Comment by Abhi-m-anue** [comment]
I have worked before in shadcn and I can create this feature. please assign me this issue

**Comment by shivamsouravjha** [comment]
sure @Abhi-m-anue !
