### ISSUE TITLE
bug: once a xlsx form is uploaded another isn't uploaded

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-frontend#2]
https://github.com/user-attachments/assets/25a036cc-cc78-4f34-9e12-d8bfdf3b5a5d

**Comment by PHANTOMFALCON** [comment]
Can I try this one time I think I can complete this task, but for this, can you give some more context regarding this, when I will get the context I will open my pull request.

**Comment by shivamsouravjha** [comment]
Sure @PHANTOMFALCON you can work on this 

please try uploading the sample xlsx file in the ui https://stock-frontend-one.vercel.app/

once you upload it and get the response, it won't let you upload again

**Comment by PHANTOMFALCON** [comment]
I am sorry for the late response but can I start this work in 3-4 days Currently my Mid-semester exams are going on
and it is really time-consuming for me, but I guarantee to check this issue after that. But during that time can you give me more insight about this xlsx upload system?

**Comment by shivamsouravjha** [comment]
sure thing take your time

what insight do you need? you can try uploading xlsx form on the website to understand the issue in detail

**Comment by PHANTOMFALCON** [comment]
hi @shivamsouravjha i checked it and the upload is working properly, please give me any other contact link like discord or something so that I can show it to you

**Comment by shivamsouravjha** [comment]
In the same upload try uploading again 

in the attached video too problem happens after first upload.
 Also we should give option to clear the file (currently nothing like that is present)

**Comment by PHANTOMFALCON** [comment]
and can you please connect with me on discord?

**Comment by shivamsouravjha** [comment]
https://www.linkedin.com/in/shivamsouravjha?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app


x.com/ShivamSouravJha

**Comment by PHANTOMFALCON** [comment]
Let me try this and get back to you

**Comment by shivamsouravjha** [comment]
refer video posted in description, once a file is uploaded its name is lt.xlsx after upload dsp file the data doesn't change(see how zomato stock is still there) meaning the xlsx wasnt either sent or response not processed. 

Video has all the reference needed.

**Comment by shivamsouravjha** [comment]
this is fixed wth the latest update
