### ISSUE TITLE
revamp: ui for better experience 

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-frontend#3]
* Remove agreement section
* Instead of showing react app should show ~ Mutual Stocks

**Comment by anushree0809** [comment]
Hi, I would like to take up this issue.
1. For the first task, the agreement button should be removed entirely? Or it should be placed somewhere else?
2. Just to confirm, the title should be 'Mutual Stocks' instead of 'React App'?

**Comment by shivamsouravjha** [comment]
the ui has been revamped a bit , now instead of vite + react it can be fundSight! https://stock-frontend-one.vercel.app/

**Comment by kmahesh18** [comment]
@shivamsouravjha assign me

**Comment by shivamsouravjha** [comment]
this has been solved @kmahesh18
