### ISSUE TITLE
Google log in does not work.

### ISSUE THREAD

**Issue by devjayprakash** [shivamsouravjha/stock-frontend#32]
<img width="1015" alt="Screenshot 2024-10-10 at 6 11 36 PM" src="https://github.com/user-attachments/assets/6ab89e79-09d7-4583-b177-7c036c6aec00">

**Comment by devjayprakash** [comment]
I'm running it on Production.

**Comment by shivamsouravjha** [comment]
is this the url https://www.stocksight.online/?

**Comment by shivamsouravjha** [comment]
any update @devjayprakash ?

**Comment by devjayprakash** [comment]
Worked on this link . I guess I was checking on vercel link
