### ISSUE TITLE
bug: no functional home button

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-frontend#33]
* Incase if the xlsx is loaded and I try to clear the screen by clicking home button , its non -functional.

**Comment by shivamsouravjha** [comment]
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/4662fe6b-c93e-4f77-a12d-09e3ccc7fce7">
this home button is non functional.

**Comment by iambijayd** [comment]
I think it's due to the stock data being rendered on the same `'/'` route. We can create separate routes for the stocks data getting rendered and file upload page where file upload can be `'/'` and stock data being `'/stocks'` OR set stock details to an `'[]'` which will render the upload page.

**Comment by shivamsouravjha** [comment]
the other one is a better approach to rather re-render

**Comment by iambijayd** [comment]
![ScreenRecording2024-10-11121709-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/8dab4ad7-6779-4f57-85f3-5478c4eb2625)
Check this

**Comment by Abhi-m-anue** [comment]
Hey your fix seems good. 

I added the client ID from google cloud and tried to run the project locally regarding another issue. Though the site was running ok, it threw Internal server error with no error text, when I tried to sign-in. 
Can you explain what you did, or if possible update the readme file with a step-by-step guide

**Comment by iambijayd** [comment]
I think my changes has nothing to do with that issue as those are local changes and i haven't raised a PR yet.

**Comment by Abhi-m-anue** [comment]
I'm not saying you did something. 
I tried to run the project locally with my own google client id, and it threw an error. I'm asking can you describe the steps you did by which you were able to run the project locally.

**Comment by iambijayd** [comment]
sorry, I misunderstood but as my fix doesn't involve anything with google login. I haven't used it but I am having same issue while trying to login with google locally. You can check if same issue persists on prod app. https://www.stocksight.online/ check this too #32

**Comment by shivamsouravjha** [comment]
hey @iambijayd i think there's a miscommunication, let's not redorect to other page, rather set it to empty object on the same page.

@Abhi-m-anue what's the error you face?

VITE_GOOGLE_CLIENT_ID=
VITE_GOOGLE_REDIRECT_URL=
VITE_GA_TRACKING_ID=


you need these 3 to do the google sign in (client id and redirect url can be created from google oauth screen

**Comment by bhavy3103** [comment]
> ![ScreenRecording2024-10-11121709-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/110587589/375650729-8dab4ad7-6779-4f57-85f3-5478c4eb2625.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjkwNTQsIm5iZiI6MTcyODcyODc1NCwicGF0aCI6Ii8xMTA1ODc1ODkvMzc1NjUwNzI5LThkYWI0YWQ3LTY3NzktNGY1Ny04NWYzLTU0NzhjNGViMjYyNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMDI1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmI2M2UwNDkzZWZjZWZiMmY1NDdmOGY1ZWY3NTg3YTA1NzEzNTZmOGZhZjJiNzA2MjhiMDYyNjE5ZmY5NmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vJ9tVUDpS5KxJEEDJDTLXxEDJ7jr8zqA4YehGYJkEQY) [ ![ScreenRecording2024-10-11121709-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/110587589/375650729-8dab4ad7-6779-4f57-85f3-5478c4eb2625.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjkwNTQsIm5iZiI6MTcyODcyODc1NCwicGF0aCI6Ii8xMTA1ODc1ODkvMzc1NjUwNzI5LThkYWI0YWQ3LTY3NzktNGY1Ny04NWYzLTU0NzhjNGViMjYyNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMDI1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmI2M2UwNDkzZWZjZWZiMmY1NDdmOGY1ZWY3NTg3YTA1NzEzNTZmOGZhZjJiNzA2MjhiMDYyNjE5ZmY5NmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vJ9tVUDpS5KxJEEDJDTLXxEDJ7jr8zqA4YehGYJkEQY) ](https://private-user-images.githubusercontent.com/110587589/375650729-8dab4ad7-6779-4f57-85f3-5478c4eb2625.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjkwNTQsIm5iZiI6MTcyODcyODc1NCwicGF0aCI6Ii8xMTA1ODc1ODkvMzc1NjUwNzI5LThkYWI0YWQ3LTY3NzktNGY1Ny04NWYzLTU0NzhjNGViMjYyNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMDI1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmI2M2UwNDkzZWZjZWZiMmY1NDdmOGY1ZWY3NTg3YTA1NzEzNTZmOGZhZjJiNzA2MjhiMDYyNjE5ZmY5NmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vJ9tVUDpS5KxJEEDJDTLXxEDJ7jr8zqA4YehGYJkEQY) [ ](https://private-user-images.githubusercontent.com/110587589/375650729-8dab4ad7-6779-4f57-85f3-5478c4eb2625.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjkwNTQsIm5iZiI6MTcyODcyODc1NCwicGF0aCI6Ii8xMTA1ODc1ODkvMzc1NjUwNzI5LThkYWI0YWQ3LTY3NzktNGY1Ny04NWYzLTU0NzhjNGViMjYyNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMDI1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmI2M2UwNDkzZWZjZWZiMmY1NDdmOGY1ZWY3NTg3YTA1NzEzNTZmOGZhZjJiNzA2MjhiMDYyNjE5ZmY5NmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vJ9tVUDpS5KxJEEDJDTLXxEDJ7jr8zqA4YehGYJkEQY) Check this

can you please provide excel here which you used in generating details

**Comment by bhavy3103** [comment]
@iambijayd can you please provide excel which you used?

**Comment by ayushmanyd** [comment]
If this issue has not resolved yet, I have a solution & its working fine, if you want I can resolve this issue.
I did some changes in Navbar.jsx.

**Comment by shivamsouravjha** [comment]
Sure this isn’t resolved yet! You can fix it

**Comment by ayushmanyd** [comment]
But it will reload the page every time we click on the logo or home. If that's ok then I'll create a pr.

**Comment by ayushmanyd** [comment]
Should I create the PR @shivamsouravjha ?

**Comment by shivamsouravjha** [comment]
yes that seems to be perfect @ayushmanyd ! when home is clicked or logo is just resetting this is what we need.
