### ISSUE TITLE
Feat: add disclaimer that this is just for education purposes

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-frontend#37]
Disclaimer

The information and ratings provided on this platform are for educational and informational purposes only. The ratings, analysis, and stock details are based on publicly available information and proprietary algorithms designed to simulate the analysis process for educational purposes. The platform does not provide financial advice, recommendations, or professional investment services.

We are not licensed as a Registered Investment Advisor or any other regulated financial entity under SEBI or any other financial regulatory authority. The platform should not be used as the basis for making any financial or investment decisions. Users are strongly advised to consult with a certified financial professional before making any actual investments.

By using this platform, you acknowledge that the information presented is for learning and demonstration purposes only, and any decisions made based on this information are done at your own risk.

**Comment by guptushar27** [comment]
@shivamsouravjha hii please assign this to me

**Comment by shivamsouravjha** [comment]
there's already a pr here https://github.com/shivamsouravjha/stock-frontend/pull/47 but PRs would be merged on first come first merge basis(the best pr would be merged)
