### ISSUE TITLE
feat: add link of github(both frontend and backend to increase contributors)

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-frontend#38]

**Comment by ayushmanyd** [comment]
Can you provide some context for this issue, What to add, where to add?

**Comment by shivamsouravjha** [comment]
In the bottom of the page we can add this. We can have links like - Help build us the  backend and Revamp the UI (both links in the footer ) about the disclaimer and below the stock sight logo (in the area where we have copyright sign)

**Comment by ayushmanyd** [comment]
Sure a rough sketch is below, and please give me the links and tell if something has to be changed in the Anchor text.

![image](https://github.com/user-attachments/assets/b6bd9672-74a3-4714-8847-7c12499fca35)

Please assign this issue to me.

**Comment by shivamsouravjha** [comment]
This looks perfect!

**Comment by ayushmanyd** [comment]
Can you provide the links?

**Comment by shivamsouravjha** [comment]
For frontend we use this repo link

for backend this is the url https://github.com/shivamsouravjha/stock-backend


Also for backend add an emoji in the end 🛠️
For frontend we can add 📺

**Comment by ayushmanyd** [comment]
What do you think? If any changes please tell.

Big Screen:
![image](https://github.com/user-attachments/assets/c3837d1c-8a06-4446-8409-b840ccf2ae34)

Mobile screen:
![image](https://github.com/user-attachments/assets/d6c7129d-d9bd-48b8-a607-ed10ed6309c2)

**Comment by shivamsouravjha** [comment]
> for backend - help us build the backend 

rest looks perfect
