### ISSUE TITLE
Update readme for yarn based set-up

### ISSUE THREAD

**Issue by Abhi-m-anue** [shivamsouravjha/stock-frontend#40]
The installation guide in readme tells to use npm to run the project locally. But the project uses yarn (as i see yarn.lock file). This is conflicting. Update the readme file or switch to npm.

**Comment by shivamsouravjha** [comment]
Npm run dev also starts the project just leaves behind a package.json file

**Comment by Abhi-m-anue** [comment]
I was trying to set-up shadcn UI, and it has some dependencies to install. If someone uses npm to install any additional package it will try to create a package.lock.json file which conflict with the already existing yarn.lock file

**Comment by shivamsouravjha** [comment]
cool better to update the readme for yarn based setup then.
