### ISSUE TITLE
feat: add a about section in home page to tell about app.

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-frontend#49]
* Let's refactor the platform like this:-
- in home page let's just out a well defined animation and texts like https://stooler.vercel.app/ (code here https://github.com/shivamsouravjha/Stooler/tree/main/frontend) 
- in the top it will have a text like ~ Find where you money is invested and below that a button to redirect to the /scanMutualFunds page(where we will put the current home page.)
- in the new home page below that let's add an about us section ~
Our platform provides investors with insights into where mutual funds are investing their money. By leveraging mutual fund portfolio disclosures from Excel sheets or Gmail, we identify the stocks that mutual funds have invested in and provide detailed ratings based on multiple factors, including F9 scores and overall performance. This tool helps investors track mutual fund stock allocations and assess the potential of individual stocks.

**Comment by guptushar27** [comment]
kindly please assign this to me

**Comment by guptushar27** [comment]
hey can you please help me with this when i open the website in browser it show this - Missing required parameter client_id

**Comment by shivamsouravjha** [comment]
You will have to create pwn client id from google oauth and then allow it use to gmail api

**Comment by guptushar27** [comment]
ok thanks

**Comment by guptushar27** [comment]
just add a about us section .how i show you my implementation .
sorry i am new in github

**Comment by shivamsouravjha** [comment]
Not just about us but a big refactor. The description shows What we want as end result
 You can raise a pull request with your changes

**Comment by ananupam** [comment]
Hey @ayushmanyd a few suggestions-
can you place the heading at centre along with the discover more button and then move the space for animation/image to be right below that. Looks pretty good tho

**Comment by ayushmanyd** [comment]
How about this? @ananupam 

And please provide the animation/image to add below the button.

https://github.com/user-attachments/assets/10b3b0dc-2fd4-4a93-8f6b-2dbaa6a87316

**Comment by ananupam** [comment]
Yup, this works. Just raise the PR for now, I'll add the animation
Also- instead of creating a fork, just push on original repo via git push origin (or     git push --set-upstream origin 
<branchName)
