### ISSUE TITLE
remove loading logo

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-frontend#5]
While loading screen the image shows the loader like this twice which isn't a good idea.

<img width="1042" alt="image" src="https://github.com/user-attachments/assets/4aca9cee-07b5-4578-a2b3-eadb517542ec">

**Comment by Vishrut99** [comment]
Can you please assign me this work

**Comment by shivamsouravjha** [comment]
sure please free to work on it
