### ISSUE TITLE
add: preview of xlsx sheet on website

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-frontend#6]
* preview the fields of xlsx sheet in https://github.com/shivamsouravjha/stock-frontend below the upload button for ensuring users don't upload wrong sheet format

**Comment by RishabhSri17** [comment]
Hi @adaharshsingh, I would be more than happy to work on this. Could you please assign this issue to me so I can start the implementation right away?

**Comment by RishabhSri17** [comment]
I had also implemented something and working on it -
Screenshots -
![Screenshot 2024-10-09 183338](https://github.com/user-attachments/assets/efb435d6-4c7b-492c-a689-422334fe22c3)
![Screenshot 2024-10-09 183534](https://github.com/user-attachments/assets/26bf0e2e-c6ab-47fb-96f1-dc3a068769bd)

**Comment by shivamsouravjha** [comment]
looks great @RishabhSri17 !
