### ISSUE TITLE
feat: a page to list down all the stocks

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/stock-frontend#65]
* we've an endpoint called as stocklisting , place a button that would redirect to the page (can show button on somehwer wherer it directly catches eye)
* curl is curl `https://stock-backend-hz83.onrender.com/api/fetchStocks` in each set we just get 10 stocks just we've pagination as well curl -X GET `https://stock-backend-hz83.onrender.com/api/fetchStocks?pageNumber=2`

**Comment by ayushmanyd** [comment]
#### How about this? Let me know if something has to be changed.

![image](https://github.com/user-attachments/assets/f994a839-68f0-4684-8a67-f2658d37f84f)

@shivamsouravjha

**Comment by shivamsouravjha** [comment]
Are we showing the rating and f9? @ayushmanyd ?  

also instead of new column for link lets use the link in the name itself 


@Ankesh2004 this would be pn first come first serve basis feel free to raise a pr

**Comment by ayushmanyd** [comment]
The API response has so many thing, should I display all?

Link in new column: Initially I thought the same but in Results page, Links are displayed like this so I changed my mind & applied  the same.

@shivamsouravjha

**Comment by shivamsouravjha** [comment]
Nope link should be in the name , we can show just main fields like stock name, Category , rating  and stock rate 
Rest everything can be otpional (like a checkbox in top)

**Comment by ayushmanyd** [comment]
But category & rating is not in API response

Updated:
![image](https://github.com/user-attachments/assets/32a6f2b2-8643-414b-b932-1d9e77f73465)

**Comment by shivamsouravjha** [comment]
hey @ayushmanyd i think it is there 
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/80f57e63-db1f-4ced-a892-2e2a125e6fdc">

also stock rate is a rating we give not the price///and category is the market cap you gave..have more fields in general for future, for  example if I add a field from backend it should automatically be present in check box without having to manually update in ui

**Comment by ayushmanyd** [comment]
Got it.

**Comment by shivamsouravjha** [comment]
Looks greay

**Comment by ayushmanyd** [comment]
Should I raise the PR?

**Comment by shivamsouravjha** [comment]
Yes
